# Stage 1: Build dependencies
FROM node:22-alpine AS builder

WORKDIR /tmp
COPY . .
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm build:auth:prod

# Stage 2: Final runtime image
FROM node:22-alpine


# Install bash
RUN apk add --no-cache bash

WORKDIR /app
COPY --from=builder tmp/node_modules ./node_modules
COPY --from=builder tmp/dist/apps/auth-service ./auth-service
COPY /contract /app/contract
RUN rm -rf /tmp

EXPOSE 3001
CMD ["node", "auth-service/src/main"]
