
# Stage 1: Build dependencies
FROM node:22-alpine AS builder

WORKDIR /app
COPY package.json .
RUN npm install --production

# Stage 2: Final runtime image
FROM node:22-alpine

# Install bash
RUN apk add --no-cache bash

ENV SHELL=/bin/bash

WORKDIR /app
COPY --from=builder app/node_modules ./node_modules
COPY /dist/apps/tour-api ./dist/apps/tour-api
COPY /contract ./contract


EXPOSE 3002
CMD ["node dist/apps/tour-api/src/main"]
