# please build with yarn first before build docker image using this dockerfile
# yarn build:auth-api
FROM node:22-alpine
WORKDIR /app
COPY /node_modules /app/node_modules
COPY /dist /app/dist
COPY /contract /app/contract

EXPOSE 3001
CMD [ "node", "/app/dist/apps/auth-api/src/main" ]
